Grubisic_Radolovic/Grubisic_Radolovic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

Grubisic_Radolovic/main/urls.py
from django.urls import path
from .views import *

app_name = "main"

urlpatterns = [
    # Registracija
    path("register/", RegisterView.as_view(), name="register"),

    #Home
    path("", HomeView.as_view(), name="home"),

    # Filmovi
    path("films/", FilmListView.as_view(), name="film_list"),
    path("film/add/", FilmCreateView.as_view(), name="film_add"),
    path("film/<int:pk>/", FilmDetailView.as_view(), name="film_detail"),
    path("film/<int:pk>/edit/", FilmUpdateView.as_view(), name="film_edit"),
    path("film/<int:pk>/delete/", FilmDeleteView.as_view(), name="film_delete"),

    #Redateljji
    path("directors/", DirectorListView.as_view(), name="director_list"),
    path("director/add/", DirectorCreateView.as_view(), name="director_add"),
    path("director/<int:pk>/edit/", DirectorUpdateView.as_view(), name="director_edit"),
    path("director/<int:pk>/delete/", DirectorDeleteView.as_view(), name="director_delete"),
    
    # Recenzije
        path("film/<int:pk>/review/add/", ReviewCreateView.as_view(), name="review_add"),
    path("review/<int:pk>/edit/", ReviewUpdateView.as_view(), name="review_edit"),
    path("review/<int:pk>/delete/", ReviewDeleteView.as_view(), name="review_delete"),
    path("my-reviews/", UserReviewsListView.as_view(), name="user_reviews"),
]

Grubisic_Radolovic/templates/base.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Film App</title>
</head>
<body>

<nav class="navbar">
    <div class="nav-left">
        <a href="{% url 'main:home' %}">Naslovnica</a>
    </div>

    <div class="nav-right">
        <a href="{% url 'main:film_list' %}">Filmovi</a>
        <a href="{% url 'main:director_list' %}">Redatelji</a>
        {% if user.is_authenticated %}
            <a href="{% url 'main:user_reviews' %}">Moje recenzije</a>
            <form method="post" action="{% url 'logout' %}" style="background-color: #111827; display:inline;">
                {% csrf_token %}
                <button type="submit" class="btn-logout">Logout</button>
            </form>
        {% else %}
            <a class="btn-secondary" href="{% url 'login' %}">Login</a>
            <a class="btn-primary" href="{% url 'main:register' %}">Registracija</a>
        {% endif %}
    </div>
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>

</body>
</html>